### ISSUE TITLE
Experience section: How to use markdown lists?

### ISSUE THREAD

**Issue by phloose** [negrel/hugo-theme-pico#12]
Thanks for the great and simplistic theme! Like the title says, i was not able to find out how to use markdown lists in the description section a single experience. I saw that you yourself did this on you homepage negrel.dev. Could you elaborate on how to achieve this?

**Comment by negrel** [comment]
Hello and thank you !
The following code snippet is used on my website:
```toml
[[period]]
  title = "Student"
  subtitle = "[IUT Networks & Telecommunications](https://www.iut-rt.net/)"
  location = "Marseille, France"
  date_start = "2018-09-03"
  date_end = "2020-07-11"
  description = """
- OOP
- Network architecture
- Web development
  """
```
I think that the **multi-line string** (see [TOML](https://toml.io/en/) spec) is what you're looking for.
You may want  to switch to YAML if you prefer.
